USE [master]
GO

/****** Object:  Database [Directory]    Script Date: 12.04.2026 23:53:39 ******/
CREATE DATABASE [Directory]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Directory', FILENAME = N'F:\PhoneDirectory\Directory.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Directory_log', FILENAME = N'F:\PhoneDirectory\Directory_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Directory].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Directory] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Directory] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Directory] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Directory] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Directory] SET ARITHABORT OFF 
GO

ALTER DATABASE [Directory] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Directory] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Directory] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Directory] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Directory] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Directory] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Directory] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Directory] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Directory] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Directory] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Directory] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Directory] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Directory] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Directory] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Directory] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Directory] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Directory] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Directory] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [Directory] SET  MULTI_USER 
GO

ALTER DATABASE [Directory] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Directory] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Directory] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Directory] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Directory] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Directory] SET OPTIMIZED_LOCKING = OFF 
GO

ALTER DATABASE [Directory] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [Directory] SET QUERY_STORE = ON
GO

ALTER DATABASE [Directory] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO

ALTER DATABASE [Directory] SET  READ_WRITE 
GO

